export const LANGUAGE_VALUES = ["en", "bn", "mixed"] as const;
export const CHANNEL_VALUES = [
  "in_app_chat",
  "call_center",
  "email",
  "merchant_portal",
  "field_agent"
] as const;
export const USER_TYPE_VALUES = ["customer", "merchant", "agent", "unknown"] as const;
export const TRANSACTION_TYPE_VALUES = [
  "transfer",
  "payment",
  "cash_in",
  "cash_out",
  "settlement",
  "refund"
] as const;
export const TRANSACTION_STATUS_VALUES = [
  "completed",
  "failed",
  "pending",
  "reversed"
] as const;
export const EVIDENCE_VERDICT_VALUES = [
  "consistent",
  "inconsistent",
  "insufficient_data"
] as const;
export const CASE_TYPE_VALUES = [
  "wrong_transfer",
  "payment_failed",
  "refund_request",
  "duplicate_payment",
  "merchant_settlement_delay",
  "agent_cash_in_issue",
  "phishing_or_social_engineering",
  "other"
] as const;
export const SEVERITY_VALUES = ["low", "medium", "high", "critical"] as const;
export const DEPARTMENT_VALUES = [
  "customer_support",
  "dispute_resolution",
  "payments_ops",
  "merchant_operations",
  "agent_operations",
  "fraud_risk"
] as const;

export const WRONG_TRANSFER_KEYWORDS = [
  "wrong number",
  "wrong recipient",
  "wrong person",
  "wrong account",
  "wrong send",
  "wrong transfer",
  "mistake",
  "reverse it",
  "brother",
  "didn't get",
  "did not get",
  "incorrect number",
  "incorrect account",
  "incorrect person",
  "sent by mistake",
  "send by mistake",
  "mistakenly sent",
  "wrong digit",
  "wrong receiver",
  "another number",
  "another account",
  "typo",
  "mistyped",
  "mistype",
  "wrong customer",
  "reversal request",
  "reverse my transfer",
  "wrong wallet",
  "send money mistake",
  "ভুল নম্বর",
  "ভুল নাম্বার",
  "ভুল অ্যাকাউন্ট",
  "ভুল একাউন্ট",
  "ভুল করে",
  "ভুল নম্বরে",
  "ভুল নাম্বারে",
  "ভুল সেন্ড",
  "ভুল ট্রান্সফার",
  "ভুল পাঠাইছি",
  "ভুল পাঠিয়েছি",
  "ভুল পাঠালাম",
  "ভুল ওয়ালেট",
  "ভুল প্রাপক",
  "ভুল নাম্বারে টাকা",
  "ভুল নম্বরে টাকা",
  "ভুল নাম্বারে সেন্ড",
  "ভুল নম্বরে সেন্ড",
  "ভুল বিকাশ",
  "অন্য নাম্বারে",
  "অন্য নম্বরে",
  "অন্য অ্যাকাউন্ট",
  "অন্য একাউন্ট",
  "ভুল ডিজিট",
  "ভুল টাইপ",
  "টাইপিং ভুল"
] as const;

export const PAYMENT_FAILED_KEYWORDS = [
  "failed",
  "balance deducted",
  "deducted",
  "recharge",
  "failed payment",
  "unsuccessful",
  "transaction failed",
  "money deducted",
  "balance cut",
  "amount deducted",
  "cut my balance",
  "failed recharge",
  "payment fail",
  "fail payment",
  "deducted from account",
  "bill payment failed",
  "failed to pay",
  "failed transaction",
  "error in payment",
  "payment error",
  "payment rejected",
  "declined",
  "ব্যালেন্স কেটেছে",
  "ব্যালেন্স কেটে",
  "টাকা কেটেছে",
  "টাকা কেটে",
  "ফেইল",
  "অসফল",
  "মোবাইল রিচার্জ",
  "রিচার্জ ফেইল",
  "রিচার্জ সফল হয়নি",
  "লেনদেন ব্যর্থ",
  "ব্যর্থ লেনদেন",
  "টাকা কেটে নিয়েছ",
  "টাকা কেটে নিয়েছে",
  "ব্যালেন্স কেটে নিয়েছে",
  "টাকা কাটল",
  "টাকা কেটে গেল",
  "অসফল রিচার্জ",
  "বিল পেমেন্ট ব্যর্থ",
  "পেমেন্ট ফেইল"
] as const;

export const REFUND_REQUEST_KEYWORDS = [
  "refund",
  "money back",
  "changed my mind",
  "want refund",
  "request refund",
  "return my money",
  "cashback return",
  "cancel purchase",
  "refund my money",
  "get a refund",
  "product return",
  "return the payment",
  "don't want the product",
  "do not want the product",
  "cancel the order",
  "order cancellation",
  "returned product",
  "claims refund",
  "ask for refund",
  "রিফান্ড",
  "টাকা ফেরত",
  "ফেরত দিন",
  "ফেরত চাই",
  "টাকা ফেরত দিন",
  "টাকা ফেরত চাই",
  "মূল্য ফেরত",
  "পণ্য ফেরত",
  "অর্ডার বাতিল",
  "ক্রয় বাতিল",
  "ক্রয় বাতিল",
  "টাকা রিটার্ন",
  "রিটার্ন চাই",
  "রিটার্ন দিন"
] as const;

export const DUPLICATE_PAYMENT_KEYWORDS = [
  "twice",
  "duplicate",
  "deducted twice",
  "charged twice",
  "charged double",
  "double deduction",
  "duplicate charge",
  "two times",
  "same bill twice",
  "paid twice",
  "double payment",
  "twice deducted",
  "double charge",
  "multi charge",
  "two transactions",
  "double debited",
  "দুইবার কেটেছে",
  "দুইবার চার্জ",
  "ডাবল কেটেছে",
  "ডাবল চার্জ",
  "ডাবল পেমেন্ট",
  "একই পেমেন্ট দুইবার",
  "দুই বার কেটেছে",
  "দুই বার চার্জ",
  "ডাবল টাকা",
  "দুইবার টাকা কেটেছে",
  "দুই বার টাকা"
] as const;

export const MERCHANT_SETTLEMENT_KEYWORDS = [
  "settlement",
  "settled",
  "sales",
  "merchant settlement",
  "not settled",
  "settlement delay",
  "yesterday's sales",
  "sales settlement",
  "merchant sales",
  "settle to my account",
  "settlement window",
  "settlement pending",
  "delayed settlement",
  "merchant account settlement",
  "seletment",
  "সেটেলমেন্ট",
  "সেটেলমেন্ট বিলম্ব",
  "সেটেলমেন্ট পাইনি",
  "মার্চেন্ট পেমেন্ট",
  "বিক্রির টাকা",
  "মার্চেন্ট সেটেলমেন্ট",
  "সেটেলমেন্ট পেন্ডিং",
  "বিক্রয় টাকা",
  "বিক্রয় টাকা",
  "সেটেলমেন্ট হচ্ছে না",
  "সেটেলমেন্ট হয় নাই",
  "সেটেলমেন্ট হয়নি"
] as const;

export const AGENT_CASH_IN_KEYWORDS = [
  "cash in",
  "cash-in",
  "agent",
  "agent cash in",
  "cashin",
  "cash in not received",
  "agent point",
  "cash in failed",
  "agent transfer",
  "agent cashin",
  "agent money",
  "cash-in issue",
  "کیش ان",
  "ক্যাশ ইন",
  "ক্যাশ-ইন",
  "ক্যাশইন",
  "এজেন্ট",
  "এজেন্টের কাছে",
  "টাকা জমা",
  "এজেন্ট ক্যাশ ইন",
  "এজেন্ট থেকে",
  "এজেন্ট পয়েন্ট",
  "এজেন্ট পয়েন্ট",
  "এজেন্ট ক্যাশইন"
] as const;

export const PHISHING_KEYWORDS = [
  "otp",
  "pin",
  "password",
  "account will be blocked",
  "blocked if",
  "verify your account",
  "share it",
  "from bkash",
  "from bKash",
  "credential",
  "credentials",
  "security code",
  "security pin",
  "enter pin",
  "enter otp",
  "share pin",
  "share otp",
  "provide password",
  "send otp",
  "send pin",
  "whats your pin",
  "what is your pin",
  "whats your otp",
  "what is your otp",
  "caller asked",
  "asking for pin",
  "asking for otp",
  "secret code",
  "card verification",
  "card number",
  "ওটিপি",
  "পিন",
  "পাসওয়ার্ড",
  "ব্লক",
  "একাউন্ট ব্লক",
  "পিন নম্বর",
  "ভেরিফিকেশন কোড",
  "পাসওয়ার্ড",
  "পিন শেয়ার",
  "ওটিপি শেয়ার",
  "পিন দিন",
  "ওটিপি দিন",
  "পিন নাম্বার",
  "পিন কোড",
  "পিন নম্বরটি",
  "পিন ওটিপি",
  "গোপন কোড"
] as const;
